name: Core
version: '${version}'
main: me.cerial.brawlkits.core.Core
api-version: 1.17
authors: [ oCerial ]
softdepend: [ MinehutCosmetics, MinehutPlugin, ViaVersion, Vault, PlaceholderAPI ]
description: A core plugin for BrawlKits.
commands:
  messages:
    description: Manage the auto broadcast messages.
  mcversion:
    description: View a player's Minecraft version.
    aliases: [mcv]
  setspawn:
    description: Sets the spawn of the server.
  spawn:
    description: Teleports you (or another player) to spawn.
  freeze:
    description: Freezes a player for screensharing purposes.
  discord:
    description: Get our Discord invite link.
  frozenchat:
    description: Toggle your frozen chat on or off.
    aliases: [fc]
  stats:
    description: View someone's stats
    aliases: [playerstats]

  # kit commands
  deletekit:
    description: Delete a kit.
    aliases: [ delkit ]

  kit:
    description: Get a kit from a kit list.
    aliases: [ kits, kitpvp ]

  createkit:
    description: Create a new kit with a name and cooldown.
    aliases: [ newkit ]

  updatecache:
    description: Update your own cache data for some commands.
    aliases: [ updcache ]

  reloadlb:
    description: Reload all the leaderboards of the server.

permissions:
  core.trainee:
    default: op
    description: A permission which grants access to all trainee commands in this plugin.

  core.mod:
    default: op
    description: A permission which grants access to all mod commands in this plugin.

  core.smod:
    default: op
    description: A permission which grants access to all senior-mod commands in this plugin.

  core.admin:
    default: op
    description: A permission which grants access to all admin commands in this plugin.

  core.manager:
    default: op
    description: A permission which grants access to all manager commands in this plugin.

  core.owner:
    default: op
    description: A permission which grants access to all owner commands in this plugin.

  core.whitechat:
    default: op
    description: A permission which gives the player who has it white chat.