name: "Bug Report"
description: "Found a bug on our server? Report it here."
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the BrawlKits bug report section. 
        Please fill this form out honestly and in-depth. 

  - type: checkboxes
    id: checklist-1
    attributes:
      label: "Checklist"
      options:
        - label: "The issue is related ONLY to the plugins managed by Cerial (Core and Discord)"
          required: false
        - label: "I am NOT reporting an issue already posted here"
          required: false

  - type: dropdown
    id: plugin
    attributes:
      label: "On which Brawl plugin are you seeing this issue?"
      options:
        - Core (the basic plugin)
        - Discord (manages the Discord bot & linking)
    validations:
      required: true

  - type: textarea
    id: bug
    attributes:
      label: "What is the bug?"
      description: "Please elaborate as much as you can for us to patch the bug entirely."
    validations:
      required: true

  - type: textarea
    id: ogstuff
    attributes:
      label: "What is supposed to happen?"
      description: "What do you think was supposed to happen if the bug didn't exist in the first place?"
    validations:
      required: true

  - type: textarea
    id: newstuff
    attributes:
      label: "And what instead happens?"
      description: "What is the so \"unusual\" thing you get instead?"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "How to reproduce the bug?"
      description: "Provide as much details as possible, even the smallest details."
    validations:
      required: true
